run:
  concurrency: 8
  tests: true
  allow-parallel-runners: true

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
#    - depguard
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
#    - varcheck
    - whitespace
    #    - wsl
    # don't enable:
    # bug:
    # https://github.com/golangci/golangci-lint/issues/967
    #    - dupl
    # deprecated
    #    - scopelint
    # deprecated
    #    - golint
    # deprecated
    #    - interfacer
    # deprecated
    #    - maligned

  #issues:
  #  exclude-rules:
  #    - linters:
  #        - stylecheck
  #      text: "ST1001:"

linters-settings:
  wsl:
    allow-separated-leading-comment: true
    allow-trailing-comment: true
