version: '3'
services:
  group-sync:
    container_name: gitea-ldap-sync
    build: .
    image: ghcr.io/janosmiko/gitea-ldap-sync
    environment:
      DEBUG: "false"
      GITEA_TOKEN: 123456789
      GITEA_BASE_URL: https://gitea.example.com
      LDAP_URL: ldap.example.com
      LDAP_PORT: 636
      LDAP_USE_TLS: "true"
      LDAP_ALLOW_INSECURE_TLS: "true"
      LDAP_BIND_DN: cn=admin,dc=ldap,dc=example,dc=com
      LDAP_BIND_PASSWORD: SuperSecretLdapPassword123
      LDAP_USER_SEARCH_BASE: 'ou=users,dc=ldap,dc=example,dc=com'
      LDAP_USER_FILTER: '(&(objectClass=user)(memberOf=*))'
      LDAP_GROUP_SEARCH_BASE: 'ou=groups,dc=ldap,dc=example,dc=com'
      LDAP_GROUP_FILTER: '(&(objectClass=group))'
      LDAP_SUBGROUP_SEARCH_BASE: 'ou=groups,DC=ldap,DC=example,DC=com'
      LDAP_SUBGROUP_FILTER: '(&(objectClass=group)(memberOf=*))'
      CRON_TIMER: '@every 1m'
      SYNC_CONFIG_CREATE_GROUPS: "true"
      SYNC_CONFIG_FULL_SYNC: "true"
#    volumes:
#      - ./config.yaml:/etc/gitea-ldap-sync/config.yaml
