apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-group-sync
spec:
  template:
    spec:
      containers:
        - name: gitea-group-sync
          image: ghcr.io/janosmiko/gitea-group-sync:latest
          env:
            - name: GITEA_BASE_URL
              value: https://user@gitea.example.com
            - name: GITEA_TOKEN
              valueFrom:
                secretKeyRef:
                  key: gitea-token
                  name: gitea-group-sync
            - name: LDAP_URL
              value: ldap.example.com
            - name: LDAP_PORT
              value: "636"
            - name: LDAP_USE_TLS
              value: 'true'
            - name: LDAP_ALLOW_INSECURE_TLS
              value: 'false'
            - name: LDAP_BIND_DN
              value: 'cn=admin,DC=ldap,DC=example,DC=com'
            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ldap-bind-password
                  name: gitea-group-sync
            - name: LDAP_USER_SEARCH_BASE
              value: 'ou=users,DC=ldap,DC=example,DC=com'
            - name: LDAP_USER_FILTER
              value: '(&(objectClass=user)(memberOf=*))'
            - name: LDAP_USER_IDENTITY_ATTRIBUTE
              value: 'sAMAccountName'
            - name: LDAP_USER_FULLNAME
              value: 'cn'
            - name: LDAP_GROUP_SEARCH_BASE
              value: 'ou=groups,DC=ldap,DC=example,DC=com'
            - name: LDAP_GROUP_FILTER
              value: '(&(objectClass=group))'
            - name: LDAP_SUBGROUP_SEARCH_BASE
              value: 'ou=groups,DC=ldap,DC=example,DC=com'
            - name: LDAP_SUBGROUP_FILTER
              value: '(&(objectClass=group)(memberOf=*))'
            - name: LDAP_EXCLUDE_GROUPS
              value: ''
            - name: LDAP_EXCLUDE_GROUPS_REGEX
              value: ''
            - name: LDAP_EXCLUDE_SUBGROUPS
              value: ''
            - name: LDAP_EXCLUDE_SUBGROUPS_REGEX
              value: ''
            - name: CRON_TIMER
              value: '@every 1m'
            - name: SYNC_CONFIG_CREATE_GROUPS
              value: 'true'
            - name: SYNC_CONFIG_FULL_SYNC
              value: 'false'
      restartPolicy: OnFailure
  backoffLimit: 6
  completions: 1
  parallelism: 1
