name: Test
on:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GO_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
        id: go

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test ./...
